Added Show Filters option, added Year filter on posts edit page
TaxoPress/TaxoPress pull request #1463
Opened 2022-09-10 08:27 UTC by jonathanpaulbbaroma

## Description

## Benefits

## Possible drawbacks

## Applicable issues

## Checklist

- [ ] I have created a specific branch for this pull request before committing, starting off the current HEAD of `development` branch. 
- [ ] I'm submitting to the `development`, feature/hotfix/release branch. (Do not submit to the master branch!)
- [ ] This pull request relates to a specific problem (bug or improvement).
- [ ] I have mentioned the issue number in the pull request description text.
- [ ] All the issues mentioned in this pull request relate to the problem I'm trying to solve.
- [ ] The code I'm sending follows the [PSR-12](https://www.php-fig.org/psr/psr-12/) coding style.

2022-09-12 08:49 UTC, ojopaul requested changes
@jonathanpaulbbaroma Check this PR https://github.com/TaxoPress/TaxoPress/pull/1462 for example to see the PR rules.

All the template requirement are supposed to be filled to give details about your pull request.

2022-09-12 15:28 UTC, jonathanpaulbbaroma commented
Hi.
May I know if you can provide a video on steps or a guide on how actually to create a pull request?

|  | Best regards,
|    | 
| JP Baroma | Senior Website Developer |
| mobile:  +63 928-1493982 |
| phone:  +63 (052) 826- 1380 |
| ***@***.*** |
| skype:  jpbaroma |
| address: Bacacay, Albay 4509 Philippines |

 |


|
| 
|  |  | 
|  |

 |

 |

 |




 

    On Monday, September 12, 2022 at 04:49:26 PM GMT+8, ojopaul ***@***.***> wrote:  
 
 


@ojopaul requested changes on this pull request.

@jonathanpaulbbaroma Check this PR #1462 for example to see the PR rules.

All the template requirement are supposed to be filled to give details about your pull request.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-09-12 15:35 UTC, ojopaul commented
Kindly check the sample pull request I linked and edit your pull request to
include all information including description, issue link and mark the
checklist to signify adapting to the requirement.

When creating pull request, the templates are shown to you and you're
required to fill in the information before clicking on Pull request but
since you already did, edit current PR and fill in all data in the
descriptions.

If you don't know how to edit PR, check my comment on (PR #1455)

On Mon, 12 Sept 2022, 4:28 pm jonathanpaulbbaroma, ***@***.***>
wrote:

> Hi.
> May I know if you can provide a video on steps or a guide on how actually
> to create a pull request?
>
> | | Best regards,
> |    |
> | JP Baroma | Senior Website Developer |
> | mobile:  +63 928-1493982 |
> | phone:  +63 (052) 826- 1380 |
> | ***@***.*** |
> | skype:  jpbaroma |
> | address: Bacacay, Albay 4509 Philippines |
>
> |
>
>
> |
> |
> | | |
> | |
>
> |
>
> |
>
> |
>
>
>
>
>
>
> On Monday, September 12, 2022 at 04:49:26 PM GMT+8, ojopaul ***@***.***>
> wrote:
>
>
>
>
> @ojopaul requested changes on this pull request.
>
> @jonathanpaulbbaroma Check this PR #1462 for example to see the PR rules.
>
> All the template requirement are supposed to be filled to give details
> about your pull request.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TaxoPress/TaxoPress/pull/1463#issuecomment-1243911676>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV622EKCGJHDKV56OOL3MPDV55D2PANCNFSM6AAAAAAQJHT6LU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-15 03:30 UTC, jonathanpaulbbaroma commented
> 

Hi @ojopaul @stevejburge I have already updated the pull request. Looking forward for your feedback

2022-09-16 05:10 UTC, ojopaul commented
> > 
> 
> Hi @ojopaul @stevejburge I **have already updated** the pull request. Looking forward for your feedback

Hello @jonathanpaulbbaroma You just updated the requirement yesterday and not already updated :)

I'll review the PR now and drop my feedback.

In addition, when you make new changes and believe it's ready for review. click the button shown below so i'll know it's ready for review after last changes request:

![re-review](https://user-images.githubusercontent.com/92122385/190561135-ab021834-5448-4459-99cf-62253e44e291.jpg)

2022-09-16 05:17 UTC, ojopaul requested changes
Hello @jonathanpaulbbaroma I've added my feedback on code aspect but in general, the requirement wasn't to add a sample year filter but instead, to allow users to show a taxonomy filter for on Posts screen.

Kindly check the issue requirement https://github.com/TaxoPress/TaxoPress/issues/1412 and see attached image and description for better understanding.

2022-09-16 05:17 UTC, ojopaul commented on inc/functions.inc.php
> +//var_dump(get_option('taxopress_external_taxonomies')['category']['show_filters']);
`//var_dump(get_option('taxopress_external_taxonomies')['category']['show_filters']);`

Leaving debugging code in final commit is discouraged. After var_dump or doing any debug, always make sure it's removed before making your commit to development.

So, remove every instance of `var_dump` in your commit

2022-09-16 05:17 UTC, ojopaul commented on inc/functions.inc.php
> +        $query_years = $wpdb->get_results("SELECT year(post_date) as year from ".$table_prefix."posts
I don't see the reasons to query database in this requirement. I'll suggest reviewing the issue properly to understand the requirement and do it the right way.

For adding taxonomy dropdown, WordPress already provide an API `wp_dropdown_categories` which is all needed to show dropdown of taxonomies filter

2022-09-16 05:17 UTC, ojopaul commented on inc/taxonomies.php
> +                        if($taxonomy_edit){
@jonathanpaulbbaroma This whole section was removed in another PR (https://github.com/TaxoPress/TaxoPress/pull/1455) but it's part of your commit. 

Always make sure you work on updated development branch and when making commit, only commit the changes you made and no addition or subtraction of codes that are not part of the requirement.

2022-09-16 05:17 UTC, ojopaul commented on inc/functions.inc.php
> +<option value="">All years</option>
@jonathanpaulbbaroma All strings should be translation ready. Hardcoding text without passing it through translation key will make it impossible for translator to find newly added strings when translating or making update to translation files.

2022-09-19 10:58 UTC, jonathanpaulbbaroma commented
Hi @ojopaul @stevejburge Please check the new commits that I had for this PR to resolve the feedback.

2022-09-19 11:18 UTC, ojopaul requested changes
@jonathanpaulbbaroma I've updated the feedback based on new commits

2022-09-19 11:18 UTC, ojopaul commented on inc/functions.inc.php
> +                    'show_option_none' => __( 'All ' . $tax_label, 'textdomain' ),
This is not TaxoPress translation text domain

2022-09-19 11:18 UTC, ojopaul commented on inc/functions.inc.php
> +    if ($post_type == 'post'){ //only add filter to posts
I already replied your comment on the issue page.

The dropdown should be enabled on the taxonomies post types

2022-09-19 11:18 UTC, ojopaul commented on inc/functions.inc.php
> +    global $wpdb, $wp_query, $table_prefix;
This global variables were never used on the page and as a result should be removed

2023-02-10 14:37 UTC, closed without merging